parameters:
#    pure_machine_web_service.example.class: PureMachine\Bundle\WebServiceBundle\Example

services:
    pureMachine.sdk.webServiceManager:
        class: PureMachine\Bundle\WebServiceBundle\Service\WebServiceManager
        calls:
            - [setContainer, [@service_container] ]